version: "3.8"
services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: deploy/DockerfileDev
    ports:
      - "3001:3001"
    environment:
      APP_PORT: 3001
      APP_SCHEME: http
      APP_HOST: 0.0.0.0
      TOKEN_AUDIENCE: https://api.charlie.app
      TOKEN_DOMAIN: https://dev-yhfol7bv57at5lsp.au.auth0.com
      NEWS_API_KEY: 17a95863-82ec-40e0-938f-54a355bd1f59
      DATABASE_URL: file:./echo-dev.db
    volumes:
      - ./apps/backend:/app
    command: sh ./deploy/entrypoint-dev.sh

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: deploy/DockerfileDev
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:3001
    volumes:
      - ./apps/frontend:/app
    depends_on:
      - backend
    command: sh ./deploy/entrypoint-dev.sh
